version: '3'
services:
  postgis:
    image: postgis/postgis
    ports:
      - "25432:5432"
    environment:
      - "POSTGRES_USER=proyecto"
      - "POSTGRES_PASSWORD=proyectovm"
      - "POSTGRES_DB=proyectodb"
      - "DEFAULT_ENCODING=UTF8"
      # Descomenta la siguiente línea si te da un error de conexión desde QGIS que dice algo como
      # "... no pg_hba.conf entry for host "172.x.x.x", ..., SSL off"
      - "ALLOW_IP_RANGE=172.0.0.0/8"
    volumes:
      - dbdata:/var/lib/postgresql      
      - "./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql"
      - "./sql/create_views.sql:/docker-entrypoint-initdb.d/create_views.sql"
      - "./sql/fill_tables_planta0.sql:/docker-entrypoint-initdb.d/fill_tables_0.sql"
      - "./sql/fill_tables_planta1.sql:/docker-entrypoint-initdb.d/fill_tables_1.sql"
      - "./sql/fill_tables_planta2.sql:/docker-entrypoint-initdb.d/fill_tables_2.sql"
      - "./sql/fill_tables_planta3.sql:/docker-entrypoint-initdb.d/fill_tables_3.sql"
      - "./sql/fill_tables_planta4.sql:/docker-entrypoint-initdb.d/fill_tables_4.sql"
volumes:
    dbdata:
        external: true    
